### ISSUE TITLE
Dashes in the names of PSA config keys results in parsing errors

### ISSUE THREAD

**Issue by Czutowski** [DarklightGames/io_scene_psk_psa#101]
**Version:**
Blender: 4.2.0
io_scene_psk_psa: 7.1.0

**Bug:**
When i imported psk file (mesh) and psa (animation) file i got "Report: Warning Failed to read PSA config file: Source contains parsing errors: 'string'"
I tried to re-export animations and player model from umodel and it didn't work either still getting the same error.

**Screenshots:**

![obraz_2024-07-31_014939234](https://github.com/user-attachments/assets/2d276dcc-0a35-44e6-92c8-de3e2f4a0990)

**Comment by cmbasnett** [comment]
Please provide the files you are using so that I can replicate the error.

**Comment by cmbasnett** [comment]
@Czutowski Please provide the files you are using so that I can replicate the error. (PSK, PSA and config file)

**Comment by cmbasnett** [comment]
I'm going to close this issue as there is no response from the original poster.

Unless I have the source files, there's nothing I can do to replicate the error, let alone fix it.

**Comment by Czutowski** [comment]
@cmbasnett Sorry for the wait, but i didn't have time to provide files, so i do that now
Here's some animation with player model that you can test and fix the problem.
[Animations.zip](https://github.com/user-attachments/files/16536107/Animations.zip)

And again sorry for the wait.

**Comment by cmbasnett** [comment]
Thanks for providing the files! Sorry the curt response earlier, I've gotten lots of reports from people who report a bug and don't ever provide the files even weeks after so I have a personal policy of closing them if I don't hear back from the OP within a week.

The issue here is that the Python library being used to parse the animation config files doesn't support dashes in the names of keys. In this case, the keys are the bone names, and the bone names contain dashes.

Luckily, however, the config file is not really needed here at all so you can ignore the error (it is just a warning, after all). The animations are still imported correctly.

**Comment by cmbasnett** [comment]
I've committed a fix that solves the issue, and it will be in the next release after some burn-in time (I usually like to run the add-on with the fix for a while before committing it for general use).

Thank you for the report!

P.S. If you want to avoid the error showing up in the meantime, just un-check "Use Config File" in the Advanced settings of the import panel:

![image](https://github.com/user-attachments/assets/62e5ce86-efa9-4594-9ff2-5aff14122a27)
