### ISSUE TITLE
Blinking eye animations are not imported

### ISSUE THREAD

**Issue by ArduFish123** [DarklightGames/io_scene_psk_psa#108]
**Versions**
Blender: 4.2
io_scene_psk_psa: 7.1.0

**Describe the bug**
Blinking eye animations imported from Minecraft Dungeons (and probably other games) are ignored and not imported.

**To Reproduce**
1. Import the psk from the zip attached
2. Import the psa from the zip
3. Note that the eyes have no blinking animations

**Expected behavior**
The blinking eye animations are imported.

**Screenshots**

**Files**
Please post attachments of the PSK and/or PSA files that you are using to encounter the bug, if any.
[PlayerMaster.zip](https://github.com/user-attachments/files/17174703/PlayerMaster.zip)

**Additional context**

**Comment by cmbasnett** [comment]
If there are no eye blinking animations in the PSA, I reckon it's because the eye blinking is handled in another animation (or maybe even programmatically). There's also no geo on the mesh here that would deform anyways. I don't think there's anything the add-on can do for you here. The data simply isn't there.

**Comment by cmbasnett** [comment]
Going to close this, but please re-open this if you can determine that it's actually an issue with the addon and not the incoming data.
