### ISSUE TITLE
Comparation of importing between your addon (io_scene_psk_psa-master-2.0.0) VS Beffz's psk/psa import (blender3d_import_psk_psa-master)

### ISSUE THREAD

**Issue by uzublecker** [DarklightGames/io_scene_psk_psa#16]
The next issue compare the import of the newest DarklightGames addon versus Beffz's one
The largest one is from Darklight. Making the model be import with it's natural size in comparation to Beffz's addon
![image](https://user-images.githubusercontent.com/92300155/150959892-3fb9b834-8ab3-4847-99e1-22a08d3e200b.png)
![image](https://user-images.githubusercontent.com/92300155/150959961-8f9c42f1-f916-4f3e-ba05-4f226995c9f8.png)
A huge difference.

The pruporse of this issue it's to show any other internaunt the comparation of these two addons in terms of size

**Comment by mirh** [comment]
You know there's a checkbox in the beffz's plugin not to automatically rescale the model?

**Comment by cmbasnett** [comment]
I'm not sure what the purpose of this ticket is. The scale-down feature (and having it the *default*) on the Beffz addon is what I would categorize as a bug since it actively transforms the imported model in an unexpected way. There is no point in recreating questionable design decisions of similar add-ons.
