### ISSUE TITLE
Model starts out 100 times too big

### ISSUE THREAD

**Issue by AnimNyan** [DarklightGames/io_scene_psk_psa#29]
So I'm not experiencing this issue with Befzz's importer. But whenever I import something with this addon using File > Import > PSK I get a model which is 100 times bigger than it should be like it's 196m tall instead of 1.96m and I need to bring it down to normal scale for lighting. This would be fine because I can just scale down the model, but also the bones are really small. I don't know if that's related to the scaling issue but it is very difficult to select the bones which makes hard to use the model in general. But honestly very nice work on maintaining this add on thank you for all your effort!

**Comment by AnimNyan** [comment]
> Did you try the scale down checkbox?

So I think I can't find the scale down option in the latest version io_scene_pks_psa-master-4.2.0.zip which I installed the only thing I get is this when I go File > Import > PSK: https://imgur.com/a/OW14Dko

I might be missing it but I cannot find it and the panel that was in the n properties panel seems to have been cut in this fork of the psk importer.

**Comment by cmbasnett** [comment]
This addon doesn't make any attempt to modify the scale of incoming models, unlike the Befzz addon. If your PSK is coming in 100x bigger than expected, its because the model is actually that size.

The scaling option was deliberately omitted when I made this addon because I found it to be a constant source of confusion and frustration.

**Comment by mirh** [comment]
https://blender.stackexchange.com/questions/24625/change-the-scale-of-the-viewport
