### ISSUE TITLE
fmodel blendshape bug

### ISSUE THREAD

**Issue by mengtun** [DarklightGames/io_scene_psk_psa#49]
Hello, CMBASNETT ,I saw that you recently fixed a bug about the fmodel library, and would like to ask how to fix the fmodel exported PSK format model facial expression error
![N @%{0HU_%8YD580)AD 6CN](https://github.com/DarklightGames/io_scene_psk_psa/assets/131957156/b9af865c-0b58-48a6-a27a-873636953e12)

**Comment by mengtun** [comment]
My blender version is 3.6

**Comment by cmbasnett** [comment]
Can you send the PSK that has the issue?

**Comment by mengtun** [comment]
https://mega.nz/file/4BhyGZ6S#HF6993XiCdT15XDJgccPmbJNnW_-6MPBayp5jt86EfQ

**Comment by mengtun** [comment]
ok. This is a file connection. In fact, almost all PSK model faces exported with fmodel have problems

**Comment by mengtun** [comment]
Hello, I have sent the file to you

**Comment by cmbasnett** [comment]
I had a look at the file but I don't see that there is anything technically wrong with the model or the shape keys. If you have an example of what the expression should look like compared to what it showing up in Blender, I might be able to be of more help. The shape key data itself is extremely simple though so there's not much room for anything to go wrong. It's very possible that this is just how the shape key data is in the original model. All the other shape key expressions seem fine.

**Comment by cmbasnett** [comment]
Closing this as invalid. There is no bug here that I can see.

**Comment by mengtun** [comment]
sma001 model has mouth problems
![Z{U)G}JHVFDMLUYHFU8}SXP](https://github.com/DarklightGames/io_scene_psk_psa/assets/131957156/cd61f90a-cf6c-4f45-b7d1-a541cf950b37)
huixing problem:
![ZC HU5CD~S00O Q6@9%5@BN](https://github.com/DarklightGames/io_scene_psk_psa/assets/131957156/33fdf001-8003-4379-9551-216a22cb6ef7)

file link:https://mega.nz/file/VdoRBQbA#L0DTdCuPWwgDteYOtdcB8n77wlQ4BTtkEkFd4rUq6fA
This package contains the wrong model and the correct model and the software I use

**Comment by mengtun** [comment]
I'm very sorry to get back to you at this time

**Comment by mengtun** [comment]
blender error:
![7B29) HB)LOP6WC7RTKP05X](https://github.com/DarklightGames/io_scene_psk_psa/assets/131957156/41ff527e-2e33-4f02-9329-bfcc3d0d0bf8)
fmodel setting:
![L{Z%4HRZ@JGWRHR$T5~CJ`X](https://github.com/DarklightGames/io_scene_psk_psa/assets/131957156/cfc0ac13-ee35-405b-8e09-2bf871257e67)

![image](https://github.com/DarklightGames/io_scene_psk_psa/assets/131957156/adc79f48-424d-4665-b904-1219b23d7e82)

**Comment by mengtun** [comment]
> 将其关闭为无效。这里没有我可以看到的错误。

I'm sorry, but I've added some more files. Hope you can take a look.

**Comment by cmbasnett** [comment]
After doing some investigating, I think that this is actually an issue with the way that FModel (or more specifically, CUE4Parse) is exporting the morph targets for PSKs.

I noticed that the vertices that are failing to be properly morphed are _overlapping_ with other vertices (like those around the mouth, on the character you linked). I then went and had a look at how CUE4Parse is exporting the morph targets.

https://github.com/FabianFG/CUE4Parse/blob/b35b843a1193d225df8583b664ef66854557a613/CUE4Parse-Conversion/Meshes/MeshExporter.cs#L456C9-L470

In that function, for each morph datum, it does a lookup on the vertex index using it's position and makes sure that the vertex index isn't already in the morph data list. This is incorrect behavior, since it's possible that two vertices share the exact same position. This results in only 1 of the overlapping vertices ever being affected by the morph data, resulting in the errors you see after exporting the PSK into Blender.

So, to reiterate, this is a bug with CUE4Parse, the library used by FModel. I will report this as a bug for them to fix.

**Comment by cmbasnett** [comment]
I have reported the bug here: https://github.com/FabianFG/CUE4Parse/issues/106

**Comment by mengtun** [comment]
Okay thank you

**Comment by cmbasnett** [comment]
I'm going to close this as this is not an issue with this addon. Thank you for the report!
