### ISSUE TITLE
Can't import animations to armatures that are missing bones.

### ISSUE THREAD

**Issue by CraftPig** [DarklightGames/io_scene_psk_psa#53]
This issue is still present, im unable to import animations to armatures with missing bones, that exist in the anim data. There doesn't seem to be anything in the settings that im missing. Other blender psa/psk importer plugins do not have this issue.

![image](https://github.com/DarklightGames/io_scene_psk_psa/assets/56685263/7ed48858-e987-4ea9-8531-bff109e4cf71)

**Comment by mossyblog** [comment]
Same issue.

**Comment by cmbasnett** [comment]
Can you both send me the PSK and PSA you are using? I only need one pair. This was reported earlier under https://github.com/DarklightGames/io_scene_psk_psa/issues/46, but I couldn't recreate the issue with the files that were given to me.

**Comment by cmbasnett** [comment]
@CraftPig @mossyblog

**Comment by Irastris** [comment]
Gonna step in since they have yet to reply. This same issue can be observed with High on Life/High on Knife when trying to import animations belonging to Harper.

Here is the PSK and a selection of 6 PSAs:
[Harper.zip](https://github.com/DarklightGames/io_scene_psk_psa/files/12923951/Harper.zip)

**Comment by cmbasnett** [comment]
@CraftPig @mossyblog @Irastris There seems to be a misunderstanding here. What you're likely experiencing is that you have not actually selected the sequence(s) you want to import from the PSA itself. Simply selecting the file and pressing import will result in no sequences being imported because all the sequences are deselected by default.

![image](https://github.com/DarklightGames/io_scene_psk_psa/assets/5035660/37868796-5d7d-4ea7-b7b8-950dc3796c60)

The addon was initially designed around importing from PSA files with a huge number of animations (hundreds or even thousands), so by default, all sequences are deselected and the user is required to manually select which ones they want.

I will change it so that all the sequences are selected by default since I've had a number of reports that all boil down to users not realizing they have to do another step to get the sequences imported.

**Comment by cmbasnett** [comment]
Version 5.0.6 (https://github.com/DarklightGames/io_scene_psk_psa/releases/tag/5.0.6) now has the sequences selected by default. Please let me know if this fixes the issues you are having.

**Comment by Irastris** [comment]
Close, my mistake was elsewhere.

What I failed to realize was that regardless of a warning (which I was mistaken in believing to be an outright error) regarding missing bones, the addon's default behavior is to not actually assign any of the sequences to the selected armature, you instead must go into the Action Editor afterward to do so. Realizing this makes the default setting of giving the imported sequences a fake user make even more sense as well.

If a user does not have an Action Editor panel already open, or an Outliner panel in Blender File/Orphan Data mode, it can be difficult to notice whether or not the animation was actually imported. When there's no immediate feedback visible to the user for the import, other than a popup dialog that's very easy to dismiss before it's readable as a result of the mouse being in motion, it can make it seem like nothing was imported at all

Personally I'm not sure there is any way to "improve" this, I would suggest simply documenting the behavior in the README so that users are aware going in.

Regardless I want to say thank you for your amazing work! Prior to 3 days ago I'd been using another PSK importer for years which I'd shoddily modified in an attempt to streamline the process for modding Unreal Engine games. Your addon by comparison does all of the same things from the get go, and also adds new features I'd not even been aware were available such as FModel's embedded morph targets, I've been manually importing glTFs from the Umodel ACL fork all this time LMAO!

**Comment by cmbasnett** [comment]
Thank you for the kind words!

And yea, the PSA import operator explicitly doesn't try to alter the scene/dependency graph as it might create undesirable side effects to change the active action on the armature. I have updated the README to note that an additional step is required to apply the actions to the armature.

P.S. I noticed this repository got a dozen new stars in like a day, has your modding community just discovered this addon? If so, what game are you modding?

**Comment by Irastris** [comment]
Afraid any uptick in traffic you may be getting is a coincidence, but deserved none the less! The vast majority of my tinkering is private and simply for my own amusement

**Comment by cmbasnett** [comment]
@CraftPig Please let me know if any of what's written here sorts out the issue you were having. If so, I will close the issue.

**Comment by cmbasnett** [comment]
Closing the issue, as there's been no response.
