### ISSUE TITLE
Exporter PSA animations have jerky motion

### ISSUE THREAD

**Issue by NOOTLORD** [DarklightGames/io_scene_psk_psa#96]
**Versions**
Blender: 4.1.1
io_scene_psk_psa: 7.0.0

**Describe the bug**
When you export a animation as a PSA we noticed that where our hands meet the weapon grip it starts to go jerky when its imported into unreal editor for ut2004, but in the blend file the hands remain glued to the weapon as it supposed to be.

https://youtu.be/ugIJGHV2Hc4

We noticed this behavior on weapons that where exported using your plugin (it seems to effect any version that is released)

**To Reproduce**
1. Open the blend file that is attached

2. Export the mesh and animation to a psk and psa respectively

3. Import the mesh and animation into unreal editor for Unreal Tournament 2004 (could be that is also appears in other game engines that support psk, but we only found it when modding for Unreal Tournament 2004)

4. Scale up the model a bit so it won't clip and keep a eye out on the fingers around the grip of the weapon (as can be seen in the video)

**Expected behavior**
You will notice that the fingers around the gun will appear jerky and not glued to the grip as it was in the original animation

**Files**
Please post attachments of the PSK and/or PSA files that you are using to encounter the bug:
[X83_Anim8Compile.zip](https://github.com/user-attachments/files/15875876/X83_Anim8Compile.zip)

If you require more information let me know 😄

**Comment by NOOTLORD** [comment]
Update:
So it seems this issue appears when IK is involved, we are looking into this i will keep you updated 👍

**Comment by NOOTLORD** [comment]
Can confirm this is not a issue with the exporter, i exported the same mesh in blender 2.79 with its psk/psa exporter without issue.
Opened the same model into 4.1.1 with version 7.0.0 of your exporter and once again no issues, i will close the issue since i can't reproduce it.

**Comment by cmbasnett** [comment]
@NOOTLORD Sorry I'm just getting to this now, I got no notification about it.

I've encountered the same thing in my travels as well, but I had never investigated the root cause because the differences were barely perceptible.

However, I looked into it and this appears to be an issue caused by the way that the engine internally compresses the animation data. When the animation is imported, it turns each data track (location & rotation) into a curve, then steps through frame by frame to see if the inter-frame difference is below some threshold, and will cull the data on that frame.

The reason this only is noticeable when using IK is fairly straightforward. because the hands and the gun are not parented to each other and are independent. Because the movement is so slight and slow, the inter-frame differences fall below the threshold and some frames are subsequently culled. resulting in the incorrect interpolation you can see in the video you posted. This is also some "interesting" behavior where the threshold values are higher when the bone is further down the bone chain, meaning that bones closer to the root are more precise than those at the end of long bone chains (such as fingers etc).

As far as I can tell there is no way to disable this behavior through normal means. The only way I could see this being "fixable" would be to do some post-processing when exporting out of Blender, where the hierarchy is actually changed so that the hand bone is treated as though it was the child of the gun, but that would be an pretty large undertaking for relatively minor payoff. One other possibility would be to bake the animations to a re-targeted rig before exporting, though this is similarly complex and cumbersome.
