### ISSUE TITLE
Imported PSK mesh has non-functional Shape Keys

### ISSUE THREAD

**Issue by Dmgvol** [DarklightGames/io_scene_psk_psa#99]
**Versions**
Blender: 4.2
io_scene_psk_psa: 7.0.0

**Describe the bug**
When importing a `.psk` mesh which has morph/shape keys, the keys are listed but not functioning.
When adjusting the shape key values - nothing happens.
So when exporting it and importing it into UE5.2 - it says "0 morph keys".

**To Reproduce**
1. Import a `.psk` file with facial expression animation that uses morph/shape keys for animations.
2. Check the individual ShapeKeys by changing their values and check if any morph as expected.

**Expected behavior**
The expected behavior is to have functioning shape keys, so it's possible to export and import it into UE5 for further modding.

**Screenshots**
![shape](https://github.com/user-attachments/assets/aa9e2a1e-79c9-455b-b1a3-9cd2ca2632fb)
As shown above, none of the shape keys affect the imported mesh.

**Files**
PSK file:
[SK_Robocop_Head.zip](https://github.com/user-attachments/files/16281854/SK_Robocop_Head.zip)
I've attached the mentioned psk file (zipped), which I exported from the game using the latest FModel.

**Comment by cmbasnett** [comment]
This appears to be an issue with the file itself, and not the add-on. I checked the data and though the shape keys are listed, there does not appear to be any actual data to work with beyond that:

![image](https://github.com/user-attachments/assets/748eaaf0-9da4-466f-ab4f-7571eda806d2)

I would report this issue to the [FModel](https://github.com/4sval/FModel) or [CUE4Parse](https://github.com/FabianFG/CUE4Parse) teams.

Just for clarity, when you import it into UE5.2, what file format are you using? This add-on doesn't support exporting shape keys to PSK since as far as I know, nothing ingests it other than this add-on and maybe some other importers scattered about.
